RxShopyAdmin/RxShopyAdmin/Models/deal.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RxShopyAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class deal
    {
        public deal()
        {
            this.usercarts = new HashSet<usercart>();
            this.userhistories = new HashSet<userhistory>();
            this.userratings = new HashSet<userrating>();
            this.userreviews = new HashSet<userreview>();
        }
    
        public int dealId { get; set; }
        public int vendorId { get; set; }
        public int locationId { get; set; }
        public int bannerId { get; set; }
        public string name { get; set; }
        public Nullable<int> categoryId { get; set; }
        public string description { get; set; }
        public System.DateTime startsOn { get; set; }
        public System.DateTime endsOn { get; set; }
        public int count { get; set; }
        public string image { get; set; }
        public System.DateTime createdOn { get; set; }
        public bool isActive { get; set; }
        public Nullable<int> sold { get; set; }
        public float unitPrice { get; set; }
        public float discount { get; set; }
        public float sellingPrice { get; set; }
        public Nullable<bool> hasShipping { get; set; }
    
        public virtual banner banner { get; set; }
        public virtual category category { get; set; }
        public virtual location location { get; set; }
        public virtual vendor vendor { get; set; }
        public virtual ICollection<usercart> usercarts { get; set; }
        public virtual ICollection<userhistory> userhistories { get; set; }
        public virtual ICollection<userrating> userratings { get; set; }
        public virtual ICollection<userreview> userreviews { get; set; }
    }
}

RxShopyAdmin/RxShopyAdmin/Models/deals.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

RxShopyAdmin/RxShopyAdmin/Controllers/DealsController.cs
using RxShopyAdmin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RxShopyAdmin.Controllers
{
    public class DealsController : Controller
    {
        public ActionResult Index()
        {
            using (var dbCntx = new dealsEntities())
            {
                Func<deal, bool> FuncDealsWhere = delegate(deal d)
                {
                    return (d.isActive == true &&
                           d.count > d.sold &&
                           d.startsOn <= DateTime.UtcNow.IndianTime() &&
                           d.endsOn >= DateTime.UtcNow.IndianTime());
                };

                var categories = dbCntx.deals
                                 .Join(dbCntx.categories,
                                     a => a.categoryId,
                                     b => b.id,
                                     (a, b) => new { A = a, B = b })
                                 .Join(dbCntx.categoryconfigs,
                                    ab => ab.B.id,
                                    c => c.categoryId,
                                    (ab, c) => new { AB = ab, C = c })
                                 .Where(x => x.AB.A.isActive == true &&
                                             x.AB.A.count > x.AB.A.sold &&
                                             x.AB.A.startsOn <= DateTime.Now &&
                                             x.AB.A.endsOn >= DateTime.Now)
                                 .GroupBy(x => new { x.AB.B.id, x.AB.B.name })
                                 .Select(x => new CategoryDisplayConfig()
                                 {
                                     id = x.FirstOrDefault().AB.B.id,
                                     name = x.FirstOrDefault().AB.B.name,
                                     display = x.FirstOrDefault().C.displayItems,
                                     isMore = x.FirstOrDefault().C.isMore
                                 }).ToList<CategoryDisplayConfig>();
                /*
                var sqlQuery = "Select * from" +
                                "(Select B.id as id, B.name as name, C.displayItems as display, C.isMore as isMore from deal as A " +
                                "inner join category as B " +
                                "on A.categoryId = B.id " +
                                "left join categoryconfig as C " +
                                "on B.id = C.categoryId " +
                                "Where A.isActive = 1 and A.count > A.sold and A.startsOn <= now() and A.endsOn >= now() " +
                                "group by B.id, B.name) x ";

                var categories = dbCntx.Database.SqlQuery<CategoryDisplayConfig>(sqlQuery).ToList<CategoryDisplayConfig>();
                */
                return View(categories);
            }
        }

        public ActionResult update(List<CategoryDisplayConfig> obj)
        {
            using (var dbCntx = new dealsEntities())
            {
                var listCat = obj.Select(x => x.id).ToList<int>();
                var categoryConfigList = dbCntx.categoryconfigs
                                                    .Where(x => listCat.Contains(x.categoryId))
                                                    .Select(x => x)
                                                    .ToList<categoryconfig>();

                for (var i = 0; i < obj.Count; i++)
                {
                    var catItem = categoryConfigList.Where(x => x.categoryId == obj[i].id)
                                            .Select(x => x)
                                            .FirstOrDefault<categoryconfig>();

                    catItem.displayItems = obj[i].display;
                    catItem.isMore = obj[i].isMore;
                }
                dbCntx.SaveChanges();
            }
            return RedirectToAction("Index");
        }

    }

    public class CategoryDisplayConfig
    {
        public int id { get; set; }
        public string name { get; set; }
        public int display { get; set; }
        public bool isMore { get; set; }
    }
}

RxShopyAdmin/RxShopyAdmin/Views/Deals/Index.cshtml
@model List<RxShopyAdmin.Controllers.CategoryDisplayConfig>
@{
    ViewBag.Title = "Index";
}

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h4 class="page-header">Deals Config</h4>
        </div>
    </div>

    @using(Html.BeginForm("update", "Deals", FormMethod.Post, new { @id = "frm" }))
    {
        for (var i = 0; i < Model.Count; i++)
        {
            <div class="row">
                <div class="col-md-2">@Model[i].name</div>
                <div class="col-md-4">
                    @Html.DropDownListFor(x => Model[i].display, new SelectList(
                      new List<SelectListItem>{ 
                           new SelectListItem { Value = "-1" , Text = "All" },
                           new SelectListItem { Value = "4" , Text = "4" }, 
                           new SelectListItem { Value = "8" , Text = "8"},
                           new SelectListItem { Value = "12" , Text = "12"},
                           new SelectListItem { Value = "16" , Text = "16"}
                        },
                      "Value",
                      "Text",
                       Model[i].display), "Select Display Items", new { @class = "form-control", onchange="displayChanged(this)", @id =  i + "_display" })
                </div>
                <div class="col-md-4">                    
                    @Html.CheckBoxFor(x => Model[i].isMore, new { @id =   i + "_isMore", onchange="isMoreChanged(this)" })&nbsp;<label for="@(i + "_isMore")">Is More</label>
                </div>
            </div>
            @Html.HiddenFor(x => Model[i].id)
            @Html.HiddenFor(x => Model[i].name)
            <br />            
        }
        <button type="submit" class="btn btn-default btn-primary">Submit</button>
    }
</div>
@section BottomSection
{
    <script type="text/javascript">
        function displayChanged(e) {                        
            if (parseInt(e.value) == -1) {
                var temp = '#' + e.id.split('_')[0] + '_isMore';
                $('#' + e.id.split('_')[0] + '_isMore').prop('checked', false);
            }
        }

        function isMoreChanged(e) {            
            var selectVal = parseInt($('#' + e.id.split('_')[0] + '_display').val());
            
            if (selectVal == -1) {
                e.checked = false;
            }
        }
    </script>
}